apiVersion: v1
kind: Pod
metadata:
  name: microservice
  namespace: default
  labels:
    app: microservice
spec:
  containers:
  - name: microservice
    image: werneroscar/udacity-project-4:latest
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    ports:
    - containerPort:  8089
      name:  http
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: microservice
  namespace: default
spec:
  selector:
    app: microservice
  type: LoadBalancer
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: microservice
    protocol: TCP
    port: 8089
    targetPort: 8089